# Generated by Django 5.0.2 on 2024-02-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_payment'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='product_ids',
        ),
        migrations.AddField(
            model_name='payment',
            name='product_ids',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
