# Generated by Django 5.0.2 on 2024-02-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_payment_product_ids_payment_product_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='product_ids',
        ),
        migrations.AddField(
            model_name='payment',
            name='product_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
