# Generated by Django 5.0.2 on 2024-02-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_payment_product_ids_payment_product_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='product_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
