# Generated by Django 5.0.2 on 2024-03-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.IntegerField(),
        ),
    ]
